config/routes.rb
Rails.application.routes.draw do

  devise_for :employees
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routin g.html

  
  root to: "homes#index"
  
  resources :employees do
    resource :address  #:professional_details
    resource :bank_detail
    resources :homes
    resource :roles, :designations 
    get :create_address, on: :member
    collection do
      # get 'update_image'
    end
    member do
      post 'send_email'
    end
  end
  

  resources :leave_details  do
    get :show_traniee, on: :collection
    get :show_hr_leave, on: :collection
    get 'update_status'
    resource :leave_types
    resource :leave_status
  end

  resources :images

  resource :employee, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :personal_email, :personal_password

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  has_one :address, dependent: :destroy
  has_many :homes, dependent: :destroy
  has_many :leave_details,  dependent: :destroy
  has_one :professional_detail, dependent: :destroy
  has_one :bank_detail, dependent: :destroy
  belongs_to :role
  belongs_to :designation


  # attr_accessor :email, :password, :password_confirmation, :role_attributes, :designation_attributes
  # accepts_nested_attributes_for :role, :designation

 validates_uniqueness_of :email

  accepts_nested_attributes_for :bank_detail
  accepts_nested_attributes_for :professional_detail
  accepts_nested_attributes_for :address


  after_create :send_mail_to_employee

  def send_mail_to_employee
    EmployeeMailer.welcome_email(self, self.personal_email, self.personal_password ).deliver_now
  end

  def admin?
    role.name == 'admin'
  end

  def lead?
    role.name == 'lead'
  end

  def hr?
    role.name == 'hr'
  end

  def employee?
    role.name == 'employee'   
  end

end

app/controllers/employee/confirmations_controller.rb
# frozen_string_literal: true

class Employee::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employee/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employee::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employee/passwords_controller.rb
# frozen_string_literal: true

class Employee::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employee/registrations_controller.rb
# frozen_string_literal: true

class Employee::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employee/sessions_controller.rb
# frozen_string_literal: true

class Employee::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/employee/unlocks_controller.rb
# frozen_string_literal: true

class Employee::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  load_and_authorize_resource 
  skip_load_and_authorize_resource only: :create

  def index
    @employees = Employee.all
  end
  
  def show
    if current_employee.admin? || current_employee.hr? || current_employee.id == params[:id].to_i
      @employee = Employee.find(params[:id])
    else
      @employee = current_employee
      flash[:danger] = "You are not authorize to access this page"
    end
  end

  def new
    @employee = Employee.new
  end

  def create
    password_length = 6
    password = Devise.friendly_token.first(password_length)
    @employee = Employee.new(allowed_params)
    @employee.personal_password = password
    @employee.password = password
    # @employee = Employee.create(new_employee_params)
    # @employee.password = SecureRandom.hex(8)
    unless @employee.save
      flash[:danger] = @employee.errors.full_messages
      render 'new'
    else
      flash[:success] = "Thanks to create a new user!" 
      redirect_to root_path
    end 
  end

  def edit
  end

  def update
    # @employee = Employee.find(params[:id])
    # @professional_detail = @employee.create_professional_detail(professional_detail_attributes_params)
    # @professional_detail.images.create(professional_detail_params)
    if current_employee.update_with_password(allowed_params)
      bypass_sign_in current_employee
      flash[:notice] = 'Password updated.'
      redirect_to root_path
    else
      flash[:danger] = current_employee.errors.full_messages
      render 'edit'
    end 
  end

  def destroy
    @employee = Employee.find(params[:id])
    current_employee.destroy
    redirect_to root_path
  end

  private

   
    def allowed_params
      params.require(:employee).permit(:role_id, :designation_id, :email, :personal_email, :personal_password, :password, :password_confirmation, :current_password, :name, :phone, :lead)
    end
    
    # def new_employee_params
    #   params.require(:employee).permit(:role_id, :designation_id, :email, :personal_email, :personal_password, :password, :password_confirmation, :current_password, :name, :phone, :lead, bank_detail_attributes:
    #  [:account_no, :bank_name, :branch_name, :ifsc_code], address_attributes: [:house_no, :street, :local_address, :permanent_address, :city, :state, :pincode])
    # end
    # def bank_detail_params
    #   params[:employee][:bank_detail_attributes].permit(:account_no, :bank_name, :branch_name, :ifsc_code)
    # end

    # # def professional_detail_params
    # #   params[:employee][:professional_detail][:images][:name].permit(:name)
    # # end

    # # def professional_detail_attributes_params
    # #   params[:employee][:professional_detail_attributes].permit(:name, :total_experience)
    # # end

    # def address_params
    #   params[:employee][:address_attributes].permit(:house_no, :street, :local_address, :permanent_address, :city, :state, :pincode)
    # end
end

app/helpers/employees_helper.rb
module EmployeesHelper

  def employee_role id
    @role = Role.find_by_id(id)
    @role.name
  end 
  
  def employee_designation id
    @designation = Designation.find_by_id(id)
    @designation.name
  end

  def employee_lead lead_id
    @lead_employee = Employee.find_by_id(lead_id)
    if @lead_employee.present?
      @lead_employee.name
    end
  end

  def lead_list
    role_ids = Role.where(name: ["lead", "admin", "employee"]).pluck(:id)
    @employee = Employee.where(role_id: role_ids)  

  end

  def designation_list
    Designation.order(:name)
  end

  def role_list
    Role.order(:name)
  end
end

app/views/employees/_popup.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Enter Email</h4>
</div>
<div class="modal-body">
  <%= form_for :employee, :url =>  send_email_employee_path(@employee), method: :post do |f| %>
    <p>

      <%= text_field_tag :email %>
      <%= hidden_field_tag :password, @password %>

    </p>
    <div class="modal-footer">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/employees/_updateimages.html.erb
<html>
<body>
<div class ="imagesForm">
  <input type="text"class="input-large" placeholder="Caption">
  <input type="file" multiple class="input-large" placeholder="Caption">
  <button class="removeNewImage" type="button">remove</button>
</div>

app/views/employees/create.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'popup') %>");
$("#modal-window").modal('show');

app/views/employees/edit.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 align = "center"><b><i>Update Profile</i></b> </h3>
      </div>
      <br>
      <%= form_for current_employee, :url => employee_path, :action => "update_password",  method: :put, :html => {:class => "form-horizontal center"} do |f| %>
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 align = "center"><b><i>Personal Details</i></b> </h3>
            </div>
            <div class="panel-body">       
                    <div class="form-group">
                      <div class="col-md-12">
                      <%= f.label :Name, class: "col-md-0 control-label"%><br>
                      <%= f.text_field :name, class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-md-12">
                      <%= f.label :Phone, class: "col-md-0 control-label"%><br>
                      <%= f.text_field :phone, class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-md-12">
                      <%= f.label :Role, class: "col-md-0 control-label" %><br>
                      <b> <%= current_employee.role.name %></b>
                      </div>
                    </div>
   
                    <div class="form-group">
                      <div class="col-md-12">
                      <%= f.label :Designation,class: "col-md-0 control-label" %><br>
                      <b><%= current_employee.designation.name %></b>
                      </div>
                    </div>

                     <div class="form-group">
                      <div class="col-md-12">
                      <%= f.label :Lead,class: "col-md-0 control-label" %><br>
                      <b><%= employee_lead(current_employee.lead) %></b>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-md-12">
                      <%= f.label :Email, class: "col-md-0 control-label"%><br>
                      <%= f.text_field :email, class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-md-12">
                        <div class="field">
                          <%= f.label :Current_Password, class: "col-md-0 control-label"%>
                          <% if @minimum_password_length %>
                          <%= current_employee.password.inspect %>
                          <em>(<%= @minimum_password_length %> characters minimum)</em>
                          <% end %><br />
                          <%= f.password_field :current_password, autocomplete: "new-password", class: "form-control"  %>
                        </div>
                      </div>
                    </div>
  
                    <div class="form-group">
                      <div class="col-md-12">
                        <div class="field">
                          <%= f.label :Password,  "Password",  class: "col-md-0 control-label" %><br />
                          <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
                        </div>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-md-12">
                        <div class="field">
                          <%= f.label :password_confirmation, class: "col-md-0 control-label" %><br />
                          <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
                        </div>
                      </div>
                    </div>
                  
                  </div>
                </div>

               <%= f.submit "Submit", class: "btn btn-primary btn-lg center-block" %>
            <%end%>

            <div class="panel panel-primary">
              <div class="panel-body">
                <div class="row">
                  <% if current_employee.address.present? %>
                    <div class="col-sm-6 mb-3 mb-md-0">
                      <h4><b><%= link_to('Edit Address Detail',  employee_address_path(current_employee)) %></b></h4>
                    </div>
                  <%else%>
                    <div class="col-sm-6 mb-3 mb-md-0">
                      <h4><b><%= link_to('Create Address Detail', new_employee_address_path(current_employee)) %></b></h4>
                    </div>
                  <%end%>

                  <% if current_employee.bank_detail.present?%>
                    <div class="col-sm-6">
                      <h4><b><%= link_to('Edit Bank Detail',  employee_bank_detail_path(current_employee)) %></b></h4>
                    </div>
                  <% else %>
                    <div class="col-sm-6">
                      <h4><b><%= link_to('Create Bank Detail', new_employee_bank_detail_path(current_employee)) %></b></h4>
                    </div>
                  <%end%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


 

app/views/employees/index.html.erb
<div class="panel panel-primary" style="max-width: 80%";>
  <div class="panel-heading">
    <h3 align = "center"><b><i>Employee Details</i></b></h3>
  </div>
  <table class="table table-striped">
    <tr>
      <th>Name </th>
      <th>Phone</th>
      <th>Role</th>
      <th>Designation</th>
      <th>Lead</th>
      <th>Email</th>
      <th>Show_All</th>
      <th>Delete_All</th>
    </tr>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.phone %></td>
        <td><%= employee_role(employee.role_id) %></td>
        <td><%= employee_designation(employee.designation_id) %></td>
        <td><%= employee_lead(employee.lead) %></td>
        <td><%= employee.email %></td>
        <td align = "center">
          <%= link_to employee_path(employee) do %>
          <span class="glyphicon glyphicon-eye-open"></span> 
          <% end %>
        </td>
        <td align = "center">
          <%= link_to employee_path(employee), 
                method: :delete,
                data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash"></span> 
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>
<div class="footer2">
  <marquee><p><b>Employee Managment System!...</b></p></marquee>
</div>

app/views/employees/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
      <h3 align ="center"><b><i>New Employee</i></b> </h3>
      </div>
      <div class="panel-body">

      <%= form_for @employee, :url =>  employees_path, method: :post, remote: true, :html => {:class => "form-horizontal center"} do |form| %>

        <div class="form-group">

          <%= form.label :Role, class: "col-md-1 control-label" %><br>
            <div class="col-md-12">
            <%= form.collection_select :role_id, role_list,:id,:name, {include_blank: "SELECT"}, {class: "form-control"} %>
            </div>
        </div>
    
   
        <div class="form-group">
          <%= form.label :Designation, class: "col-md-1 control-label" %><br>
            <div class="col-md-12">
            <%= form.collection_select :designation_id, designation_list,:id,:name, {include_blank: "SELECT"}, {class: "form-control"} %>
            </div>
        </div>

        <div class="form-group">
          <%= form.label :Email, class: "col-md-1 control-label"%><br>
            <div class="col-md-12">
            <%= form.email_field :email,  :uniqueness => true, class: "form-control" %>
            </div>
        </div>
  
          <div class="form-group">
          <%= form.label :Lead, class: "col-md-1 control-label"%><br>
            <div class="col-md-12">
             <%= form.collection_select :lead, lead_list, :id,:name, {include_blank: "SELECT"}, {class: "form-control"} %>
            </div>
          </div>

           <%= form.button_tag "NEXT", :type => 'button', class: "btn btn-primary", 'data-toggle' => "modal", 'data-target' => "#modal-window" %>

           <div class="modal fade" id="modal-window" role="dialog">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">x</button>
                    <h4 class="modal-title" id="myModalLabel">Enter Email</h4>
                  </div>
                    <div class="modal-body">
                      <p>
                        <%= form.text_field_tag "employee[personal_email]"%>
                        <%= form.hidden_field_tag "employee[personal_password]", @password %>
                      </p>
                      <div class="modal-footer">
                        <%= form.submit %>
                      </div>
                    </div>
                </div>
            </div>
          </div> 
        <%#= form.submit "Submit", class: "btn btn-primary", 'data-toggle' => "modal", 'data-target' => "#modal-window"%>      
        <%end%>
      </div>
    </div>
  </div>
</div>

<div class="footer">
  <marquee><p><b>Employee Managment System!...</b></p></marquee>
</div>

app/views/employees/show.html.erb
<div class="panel panel-primary" style="max-width: 80%";>
  <div class="panel-heading"><h3 align = "center"><b><i> Employee Detail</i></b> </h3></div>
    <div class="row">
      <div class="col-md-4 mb-3 mb-md-0">
         <h3 align="center"><b>Personal Detail</b></h3>
          <ul class="list-group">
            
            <div class="col-md-12">
              <li class="list-group-item">
                <p align="center">
                <strong>Name:</strong>
                <%= @employee.name %>
                </p>
              </li>
            </div>

            <div class="col-md-12">
              <li class="list-group-item">
                <p align="center">
                <strong>Phone:</strong>
                <%= @employee.phone %>
                </p>
              </li>
            </div>

            <div class="col-md-12">
              <li class="list-group-item">
                <p align="center">
                <strong>Role:</strong>
               <%= @employee.role.name %>
                </p>
              </li>
            </div>
 
            <div class="col-md-12">
              <li class="list-group-item">
                <p align="center">
                <strong>Email:</strong>
                <%= @employee.email %>
                </p>
              </li>
            </div>

            <div class="col-md-12">
              <li class="list-group-item">
                <p align="center">
                <strong>Designation:</strong>
                <%= @employee.designation.name %>
                </p>
              </li>
            </div>

             <div class="col-md-12">
              <li class="list-group-item">
                <p align="center">
                <strong>Lead:</strong>
                <%= employee_lead(@employee.lead) %>
                </p>
              </li>
            </div>   
          </div>
        
          <div class="col-md-4">
          <h3 align="center"><b>Address Detail</b></h3>
          <% if  @employee.address.present? %>  
          <div class="col-md-12">
            <li class="list-group-item">
              <p align="center">
              <strong>House-no:</strong>
             <%= @employee.address.house_no %>
              </p>
            </li>
          </div>

          <div class="col-md-12">
            <li class="list-group-item">
              <p align="center">
              <strong>Street:</strong>
              <%= @employee.address.street %>
              </p>
            </li>
          </div>

          <div class="col-md-12">
            <li class="list-group-item">
              <p align="center">
              <strong>Local Address:</strong>
              <%= @employee.address.local_address %>
              </p>
            </li>
          </div>

          <div class="col-md-12">
            <li class="list-group-item">
              <p align="center">
              <strong>Permanent Address:</strong>
             <%= @employee.address.permanent_address %>
              </p>
            </li>
          </div>

          <div class="col-md-12">
            <li class="list-group-item">
              <p align="center">
              <strong>City:</strong>
             <%= @employee.address.city %>
              </p>
            </li>
          </div>

          <div class="col-md-12">
            <li class="list-group-item">
              <p align="center">
              <strong>State:</strong>
              <%= @employee.address.state %>
              </p>
            </li>
          </div>

          <div class="col-md-12">
            <li class="list-group-item">
              <p align="center">
              <strong>Pincode:</strong>
              <%= @employee.address.pincode %>
              </p>
            </li>
          </div>
          <% else %>
         <div class="col-md-12">
          <li class="list-group-item">
            <p align="center">
            <strong>Details not present</strong>
            </p>
          </li>
        </div>
          <%end%>
        </div>
      

        <div class="col-md-4">
        <h3 align="center"><b>Bank Detail</b></h3>
 
      <%if @employee.bank_detail.present?%>
        <div class="col-md-12">
          <li class="list-group-item">
            <p align="center">
            <strong>Account_no:</strong>
            <%= @employee.bank_detail.account_no %>
            </p>
          </li>
        </div>

        <div class="col-md-12">
          <li class="list-group-item">
            <p align="center">
            <strong>Bank Name:</strong>
            <%= @employee.bank_detail.bank_name %>
            </p>
          </li>
        </div>

        <div class="col-md-12">
          <li class="list-group-item">
            <p align="center">
            <strong>Branch name:</strong>
            <%= @employee.bank_detail.branch_name %>
            </p>
          </li>
        </div>

        <div class="col-md-12">
          <li class="list-group-item">
            <p align="center">
            <strong>IFSC code:</strong>
            <%= @employee.bank_detail.ifsc_code %>
            </p>
          </li>
        </div>
        <%else%>
        <div class="col-md-12">
          <li class="list-group-item">
            <p align="center">
            <strong>Details not present</strong>
            </p>
          </li>
        </div>
      <%end%>
      </div>
    </div>
  </ul>
<div class="footer">
  <marquee><p><b>Employee Managment System!...</b></p></marquee>
</div>

app/views/employees/show_image.js.erb
$(document).ready(function(){
  $('#addNewImage').click(function(){
    $('div#imageSet').append(render 'updateimages');
  });    
   $("div#imageSet").on('click', '.removeNewImage', function(){
   $(this).closest('.imagesForm').remove();
  });
});