config/routes.rb
Rails.application.routes.draw do

  devise_for :employees
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routin g.html

  
  root to: "homes#index"
  
  resources :employees do
    resource :address  #:professional_details
    resource :bank_detail
    resources :homes
    resource :roles, :designations 
    get :create_address, on: :member
    collection do
      # get 'update_image'
    end
    member do
      post 'send_email'
    end
  end
  

  resources :leave_details  do
    get :show_traniee, on: :collection
    get :show_hr_leave, on: :collection
    get 'update_status'
    resource :leave_types
    resource :leave_status
  end

  resources :images

  resource :employee, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
end

app/models/home.rb
class Home < ApplicationRecord
  belongs_to :employee, optional: true
  mount_uploader :image, ImageUploader
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # load_and_authorize_resource
# before_action :set_post, only: [:show, :edit, :update]

#   def index
#      @homes = Home.all
#   end

#   def show
    
#   end

#   def new
#     @home = Home.new
#   end

#   def create
#     @home = Home.new(home_params)
#     if @home.save
#       redirect_to home_path(@home)
#     else
#       render :edit
#     end
#   end

#   def edit
#     @home = Home.find(params[:id])
#   end

#   def update
#      if @home.update_attributes(home_params)
#       redirect_to home_path(@home)
#     else
#       render :edit
#     end
#   end

#   private 

#   def home_params
#     params.require(:home).permit(:title, :body, :image)
#   end

#   def set_post
#     @home = Home.find(params[:id])
#   end

 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
   # before_action :set_post, only: [:show, :edit, :update]
  
  def index
     @homes = Home.all
  end

  def show
    
  end

  def new
    @home = Home.new
  end

  def create
    binding.pry
    @home = Home.new(home_params)
    if @home.save
      redirect_to employee_homes_path(@home)
    else
      render :new
    end
  end

  def edit
    @home = Home.find(params[:id])
  end

  def update
     if @home.update_attributes(home_params)
      redirect_to root_path(@home)
    else
      render :edit
    end
  end

   private 

  def home_params
    params.require(:home).permit(:title, :body, :image)
  end

  # def set_post
  #   @home = Home.find(params[:id])
  # end

 
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%#= form_for :home, :url => employee_homes_path  do |f| %>
<%= form_for(@home, :url => employee_homes_path, :validate => true, :html => { :'data-ajax' => false }) do |f| %>
  
   <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
 
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
 
  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <p><%= f.submit %></p>
<% end %>

app/views/homes/_home.html.erb
<h2><%= link_to home.title, employee_homes_path(home) %></h2>
 
<p><%= truncate(home.body, length: 150) %></p>
 
<p><%= link_to 'Edit', edit_employee_home_path(home) %></p>
<hr>

app/views/homes/edit.html.erb
<h1>Edit post</h1>
 
<%= render 'form', post: @home %>

app/views/homes/index.html.erb
<h1>Dashboard</h1>
<h1>Posts</h1>
 
<%= link_to 'Add post',   new_employee_home_path(:employee_id) %>
 
<%#= render @homes %>

app/views/homes/new.html.erb
 <h1>Add post</h1>
 
<%= render 'form', post: @home %>

app/views/homes/show.html.erb
<%#= link_to 'All posts',  employee_homes_path %>
<h1><%#= @home.title %></h1>
 
<%#= image_tag(@home.image.url, alt: 'Image') if @home.image? %>
 
<p><%#= @home.body %></p>
 
<p><%#= link_to 'Edit',  edit_employee_home_path(@home) %></p>




<div id="imagess">
  <% @home.images.each do |image| %>
    <div class="image">
      <%= image_tag home.image_url.to_s %>
      <div class="name"><%= image.name %></div>
      <div class="actions">
        <%= link_to "edit", edit_employee_home_path(home) %> |
        <%= link_to "remove", home, :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>