config/routes.rb
Rails.application.routes.draw do

  devise_for :employees
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routin g.html

  
  root to: "homes#index"
  
  resources :employees do
    resource :address  #:professional_details
    resource :bank_detail
    resources :homes
    resource :roles, :designations 
    get :create_address, on: :member
    collection do
      # get 'update_image'
    end
    member do
      post 'send_email'
    end
  end
  

  resources :leave_details  do
    get :show_traniee, on: :collection
    get :show_hr_leave, on: :collection
    get 'update_status'
    resource :leave_types
    resource :leave_status
  end

  resources :images

  resource :employee, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(employee)
    employee ||= Employee.new # guest user (not logged in)
    if employee.lead?
      can [:show], Employee
      can [:show_traniee], :all
      can [:create, :read], LeaveDetail
    elsif employee.admin?
      can :manage, :all
    elsif employee.employee?
      can [:update, :show], Employee
      can [:create, :edit], Address
      can [:create, :edit], BankDetail
      can [:create, :read], LeaveDetail
    elsif employee.hr?
      can [:manage, :create], :all
      can [:show_hr_leave], LeaveDetail
    else
      cannot :manage, :all
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :employee

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_detail.rb
class BankDetail < ApplicationRecord
  belongs_to :employee

  validates :account_no, presence: true
  validates :bank_name, presence: true

  # validates_format_of :ifsc_code,:with => /^[A-Za-z]{4}0[A-Z0-9a-z]{6}$/, :multiline => true
end

app/models/designation.rb
class Designation < ApplicationRecord
  validates_uniqueness_of :name, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :personal_email, :personal_password

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  has_one :address, dependent: :destroy
  has_many :homes, dependent: :destroy
  has_many :leave_details,  dependent: :destroy
  has_one :professional_detail, dependent: :destroy
  has_one :bank_detail, dependent: :destroy
  belongs_to :role
  belongs_to :designation


  # attr_accessor :email, :password, :password_confirmation, :role_attributes, :designation_attributes
  # accepts_nested_attributes_for :role, :designation

 validates_uniqueness_of :email

  accepts_nested_attributes_for :bank_detail
  accepts_nested_attributes_for :professional_detail
  accepts_nested_attributes_for :address


  after_create :send_mail_to_employee

  def send_mail_to_employee
    EmployeeMailer.welcome_email(self, self.personal_email, self.personal_password ).deliver_now
  end

  def admin?
    role.name == 'admin'
  end

  def lead?
    role.name == 'lead'
  end

  def hr?
    role.name == 'hr'
  end

  def employee?
    role.name == 'employee'   
  end

end

app/models/home.rb
class Home < ApplicationRecord
  belongs_to :employee, optional: true
  mount_uploader :image, ImageUploader
end

app/models/image.rb
class Image < ApplicationRecord
  require 'carrierwave/orm/activerecord'
  
  belongs_to :imageable, polymorphic: true
  mount_uploader :name, ProfessionalDetailUploader

end

app/models/leave_detail.rb
class LeaveDetail < ApplicationRecord
  belongs_to :employee
  # has_one :leave_status
  # has_one :leave_type
  belongs_to :leave_status
  belongs_to :leave_type
  
  validates :absent_to, :absent_from, :leave_apply_for_days, presence: true

  validates :avl_mobile,   :presence => {:message => 'hello world, bad operation!'},
                     :numericality => true,
                     :length => { :minimum => 10, :maximum => 15 }

  validates_format_of :avl_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  scope :all_except, ->(employee) { where.not(id: employee) }

  before_validation :absent_from_after_absent_to

  def leavedetail_role
    self.employee.role.name
  end

  def leavedetail_name
    self.employee.name
  end
  
  def leavedetail_designation
    self.employee.designation.name
  end

  private

  def absent_from_after_absent_to
    if leave_apply_for_days < (absent_from - absent_to).to_i
      errors.add(:absent_to, "Apply leave days is greater than leave apply for the days")

    elsif absent_from < absent_to
      errors.add(:absent_from, "must be after the start date")
   

    elsif absent_to.present? && absent_to < Date.today
      errors.add(:absent_to, "Date can't be in the past")
    

    elsif absent_from.present? && absent_from < Date.today
      errors.add(:absent_from, "can't be in the past")
    end
  end
end

app/models/leave_status.rb
class LeaveStatus < ApplicationRecord 
  validates_uniqueness_of :name, dependent: :destroy
  belongs_to :leave_detail
end

app/models/leave_type.rb
class LeaveType < ApplicationRecord
  belongs_to :leave_detail
  validates_uniqueness_of :name, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord

  mount_uploader :image, ImageUploader
end

app/models/professional_detail.rb
class ProfessionalDetail < ApplicationRecord
  belongs_to :employee
  has_many :images, as: :imageable
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
end

app/models/role.rb
class Role < ApplicationRecord
  validates_uniqueness_of :name, dependent: :destroy
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-warning"
    end
  end
  
end

app/helpers/employees_helper.rb
module EmployeesHelper

  def employee_role id
    @role = Role.find_by_id(id)
    @role.name
  end 
  
  def employee_designation id
    @designation = Designation.find_by_id(id)
    @designation.name
  end

  def employee_lead lead_id
    @lead_employee = Employee.find_by_id(lead_id)
    if @lead_employee.present?
      @lead_employee.name
    end
  end

  def lead_list
    role_ids = Role.where(name: ["lead", "admin", "employee"]).pluck(:id)
    @employee = Employee.where(role_id: role_ids)  

  end

  def designation_list
    Designation.order(:name)
  end

  def role_list
    Role.order(:name)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </button>   
  </div>
  <div id="navbar" class="navbar-collapse collapse">
    <div class ="link">
      <ul class="nav navbar-nav navbar-right">
        <% if employee_signed_in? %>
        <li><h3 class=".text-left"><%= current_employee.role.name %></h3></li>
          <% if current_employee_role_is_admin || current_employee_role_is_hr %>
            <% if current_employee_role_is_hr %>
            <li><%= link_to('Apply Leave',  new_leave_detail_path(id: current_employee.id)) %></li>
            <li><%= link_to('Edit Profile', edit_employee_path(id: current_employee.id)) %></li>
            <li><%= link_to('Leave Status',  show_hr_leave_leave_details_path) %></li>
            <% end %>
             <li><%= link_to('Home',root_path) %></li>
            <li><%= link_to('Show Leave', leave_details_path) %></li>
            <li><%= link_to('All Users', employees_path) %></li>

            <% if can? :create, current_employee %>
            <li><%= link_to('New_Employee', new_employee_path) %></li>
            <% end %>
          <% else %>  
            <li><%= link_to('Home',root_path) %></li>
            <li><%= link_to('Show Profile', employee_path(id: current_employee.id)) %></li>
            <li><%= link_to('Leave Status',  leave_details_path(id: current_employee.id)) %></li>
            <li><%= link_to('Apply Leave',  new_leave_detail_path(id: current_employee.id)) %></li>

            <% if can? :update, current_employee %>
            <li><%= link_to('Edit Profile', edit_employee_path(id: current_employee.id)) %></li>
            <% end %>
              <% if current_employee_role_is_lead %>
                <li><%= link_to('Show tranees',   show_traniee_leave_details_path) %></li>
              <% end %>
          <% end %>
          <li><%= link_to "Sign out", destroy_employee_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to('Sign in', new_employee_session_path) %></li>
        <% end %> 
      </ul>
    </div>
  </div> 
</nav>  

app/views/layouts/_modal.html.erb
<!-- ADD MORE -->
<div id="testmodal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-test">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Confirmation</h4>
      </div>
      <div class="modal-body">
          <p>Do you want to save changes you made to document before closing?</p>
          <p class="text-warning"><small>If you don't save, your changes will be lost.</small></p>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Employee</title>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>
  <body>
    <%= render "layouts/header" %>    
    <% flash.each do |key, value| %>
      <div class="message">
        <div class="alert alert-success  <%= key %> fade in">
          <a class="close" href="#">&times</a>
          <center><strong><%= value %></strong></center>
       </div>
      </div>
    <% end %>  
    <%= yield %>
  </body>
</html>
<script type="text/javascript">
  $(document).ready(function(){
    setTimeout(function(){
      $('.alert').remove();
    }, 3000);
  })
</script>